name: Push Whisper to NuGet

on:
  push:
    branches: [ "master" ]
    paths:
      - 'src/**'
      - '.github/workflows/publish.yml' 

jobs:
  build:
    permissions:
      id-token: write 
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
    - name: Build
      run: dotnet build -c Release
    - name: Test
      run: dotnet test -c Release --no-build
    - name: Package
      run: dotnet pack -c Release --no-build --output .
    - name: NuGet login (OIDC → temp API key)
      uses: NuGet/login@v1
      id: login
      with:
        user: nevsnirG
    - name: push to nuget
      run: dotnet nuget push "*.nupkg" --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate